/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false cloudflare-env.d.ts` (hash: 6f42615289426a395f8a1986c8fd4863)
interface __BaseEnv_Env {
	BOOKING_FILES: R2Bucket;
	BOOKINGS_DB: D1Database;
	LEAD_RECIPIENT: "info@giccmasjid.org";
	MAIL_FROM_NAME: "GICC Website";
}
declare namespace Cloudflare {
	interface PreviewEnv {
		BOOKING_FILES: R2Bucket;
		BOOKINGS_DB: D1Database;
		LEAD_RECIPIENT: "info@giccmasjid.org";
		MAIL_FROM_NAME: "GICC Website";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
