/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false cloudflare-env.d.ts` (hash: 1e409063a6e4a55dd797f5f3eaba92e7)
interface __BaseEnv_Env {
	BOOKING_FILES: R2Bucket;
	BOOKINGS_DB: D1Database;
	LEAD_RECIPIENT: "secretary@giccmasjid.org";
	MAIL_FROM_NAME: "GICC Website";
}
declare namespace Cloudflare {
	interface PreviewEnv {
		BOOKING_FILES: R2Bucket;
		BOOKINGS_DB: D1Database;
		LEAD_RECIPIENT: "secretary@giccmasjid.org";
		MAIL_FROM_NAME: "GICC Website";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
